# Generated by Django 5.0.6 on 2024-07-03 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_registration_parol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='ism',
            new_name='Имя',
        ),
    ]
