# Generated by Django 5.0.6 on 2024-07-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_ism_registration_имя'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='familiya',
            new_name='Напровление',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='telefon',
            new_name='Телефон',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='it',
            new_name='Фамилия',
        ),
    ]
