# Generated by Django 5.0.6 on 2024-07-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_имя_registration_familiya_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='familiya',
            new_name='Имя',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='ism',
            new_name='Напровление',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='telefon',
            new_name='Телефон',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='it',
            new_name='Фамилия',
        ),
    ]
