# Generated by Django 5.0.6 on 2024-07-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_familiya_registration_имя_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Имя',
            new_name='familiya',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Напровление',
            new_name='ism',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Фамилия',
            new_name='it',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Телефон',
            new_name='telefon',
        ),
    ]
