# Generated by Django 5.0.6 on 2024-07-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='views',
        ),
        migrations.AddField(
            model_name='course',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
